[env.preview]
name = "language-trainer-preview"
route = "*\\.language-trainer.pages.dev/*"
workers_dev = true

[env.production]
name = "language-trainer"
route = "language-trainer.pages.dev/*"
workers_dev = false
