[env.preview]
name = "language-trainer-preview"
compatibility_date = "2023-08-17"
workers_dev = true
account_id = "57aeeb8bc8b9a7f109b724fe491b85f1"

[env.production]
name = "language-trainer"
compatibility_date = "2023-08-17"
route = "language-trainer.pages.dev/*"
workers_dev = false
